from http.server import BaseHTTPRequestHandler
import json, base64, smtplib, os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.image import MIMEImage
import requests

GEMINI_KEY = os.environ.get("GEMINI_API_KEY", "")
GEMINI_URL = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key={GEMINI_KEY}"

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASS = os.environ.get("SMTP_PASS", "")
TO_EMAIL = os.environ.get("TO_EMAIL", "")

def build_prompt(space_type, description):
    """Build a space transformation prompt based on what the customer wants."""
    space = space_type.strip() if space_type else "home space"
    desc = description.strip() if description else "general cleaning and organizing"
    
    return f"""You are a professional home stylist and organizer. A customer has uploaded a photo of their {space} and described what they want. Transform the photo according to their description.

CUSTOMER'S REQUEST for their {space}: {desc}

CRITICAL RULES:
- Keep walls, floors, windows, doors, and fixed structures EXACTLY as they appear
- Do NOT change the perspective, angle, or lighting of the photo
- Organize, clean, and beautify the space according to the description
- Make the result look like a real photograph
- The space should look professionally cleaned, organized, and beautiful
- Match existing colors and materials where not specified otherwise
- For outdoor spaces: use realistic regional plants and materials
- For indoor spaces: use realistic organizing solutions, fresh linens, clean surfaces
- Follow the customer's description as closely as possible while keeping the result photorealistic

Return the transformed image showing the completed work."""

def call_gemini(image_base64, prompt):
    if not GEMINI_KEY:
        raise Exception("GEMINI_API_KEY not configured")
    
    payload = {
        "contents": [{
            "parts": [
                {"text": prompt},
                {"inlineData": {"mimeType": "image/jpeg", "data": image_base64}}
            ]
        }],
        "generationConfig": {
            "responseModalities": ["TEXT", "IMAGE"]
        }
    }
    
    resp = requests.post(GEMINI_URL, json=payload, timeout=90)
    data = resp.json()
    
    if "candidates" not in data:
        raise Exception(f"Gemini API error: {data.get('error', data)}")
    
    parts = data["candidates"][0]["content"]["parts"]
    result = {"text": "", "image_base64": None}
    
    for part in parts:
        if "text" in part:
            result["text"] = part["text"]
        if "inlineData" in part and "data" in part["inlineData"]:
            result["image_base64"] = part["inlineData"]["data"]
    
    return result

def send_email(name, email, phone, space_type, description, before_base64, after_base64):
    """Send estimate request email with BOTH before and after images."""
    if not SMTP_USER or not SMTP_PASS:
        print("SMTP not configured — skipping email")
        return
    
    msg = MIMEMultipart("mixed")
    msg["From"] = f"A Mom & A Mop <{SMTP_USER}>"
    msg["To"] = TO_EMAIL
    msg["Subject"] = f"🧹 New Visualization Request — {name or 'New Customer'}"

    space = space_type or "(not specified)"
    desc = description or "(no description provided)"

    html = f"""<html><body style="font-family:sans-serif">
<h2 style="color:#ec4899">🧹 New Space Visualization Request</h2>
<table style="border-collapse:collapse;margin:15px 0">
<tr><td style="padding:6px 12px;font-weight:bold">Name:</td><td>{name or 'N/A'}</td></tr>
<tr><td style="padding:6px 12px;font-weight:bold">Email:</td><td>{email or 'N/A'}</td></tr>
<tr><td style="padding:6px 12px;font-weight:bold">Phone:</td><td>{phone or 'N/A'}</td></tr>
<tr><td style="padding:6px 12px;font-weight:bold">Space Type:</td><td>{space}</td></tr>
</table>
<h3>Customer's Request:</h3>
<pre style="background:#fce7f3;padding:12px;border-radius:6px;white-space:pre-wrap">{desc}</pre>
<h3>Images:</h3>
<p>📸 <strong>BEFORE</strong> — original photo (what needs work)</p>
<p>✨ <strong>AFTER</strong> — AI visualization (the transformation)</p>
<hr>
<p style="color:#888;font-size:12px">
  <strong>Use the BEFORE photo to estimate pricing</strong> — the AFTER shows the goal.<br>
  Generated by A Mom & A Mop Visualizer · Greenville, SC
</p>
</body></html>"""

    msg.attach(MIMEText(html, "html"))

    if before_base64:
        img = MIMEImage(base64.b64decode(before_base64), _subtype="jpeg")
        img.add_header("Content-Disposition", "attachment", filename="before_original.jpg")
        msg.attach(img)

    if after_base64:
        img = MIMEImage(base64.b64decode(after_base64), _subtype="jpeg")
        img.add_header("Content-Disposition", "attachment", filename="after_visualization.jpg")
        msg.attach(img)

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.starttls()
        server.login(SMTP_USER, SMTP_PASS)
        server.send_message(msg)

class handler(BaseHTTPRequestHandler):
    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.end_headers()
    
    def do_POST(self):
        if self.path != "/api/visualize":
            self._respond(404, {"success": False, "error": "Not found"})
            return

        content_type = self.headers.get("Content-Type", "")
        if "application/json" not in content_type:
            self._respond(400, {"success": False, "error": "Expected JSON"})
            return

        content_length = int(self.headers.get("Content-Length", 0))
        if content_length > 10_000_000:
            self._respond(413, {"success": False, "error": "Request too large"})
            return

        body = self.rfile.read(content_length)
        try:
            data = json.loads(body)
        except json.JSONDecodeError:
            self._respond(400, {"success": False, "error": "Invalid request format."})
            return

        image_base64 = data.get("image", "")
        space_type = data.get("space_type", "")
        description = data.get("description", "")
        name = data.get("name", "")
        email = data.get("email", "")
        phone = data.get("phone", "")

        # Strip data:image prefix
        if "," in image_base64:
            image_base64 = image_base64.split(",", 1)[1]

        if not image_base64:
            self._respond(400, {"success": False, "error": "No image provided."})
            return

        try:
            img_bytes = len(base64.b64decode(image_base64))
        except Exception:
            self._respond(400, {"success": False, "error": "Invalid image data."})
            return

        if img_bytes > 7_000_000:
            self._respond(400, {"success": False, "error": "Image too large. Please use a photo under 7MB."})
            return

        try:
            prompt = build_prompt(space_type, description)
            result = call_gemini(image_base64, prompt)

            email_sent = True
            try:
                send_email(name, email, phone, space_type, description, 
                          before_base64=image_base64,
                          after_base64=result["image_base64"])
            except Exception as email_err:
                print(f"Email failed: {email_err}")
                email_sent = False

            response = {
                "success": True,
                "after_image": result["image_base64"],
                "description": result.get("text", "")
            }
            if not email_sent:
                response["email_warning"] = "Visualization created but email notification failed. The owner will still see your request."

            self._respond(200, response)
        except Exception as e:
            print(f"Visualization error: {e}")
            self._respond(500, {"success": False, "error": "We couldn't generate your visualization. Please try again."})
    
    def _respond(self, status, body):
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(json.dumps(body).encode())
